modLoader = "javafml"
loaderVersion="${loader_version_range}"
license = "${mod_license}"
issueTrackerURL="${mod_issue_tracker_url}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL="${mod_url}"
logoFile = "piercingpaxels.png"
credits = "${mod_credits}"
authors = "${mod_author}"
displayTest="MATCH_VERSION"

description='''${mod_description}'''
[[dependencies.'${mod_id}']]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.'${mod_id}']]
    modId = "minecraft"
    mandatory = true
    versionRange = "${forge_minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.'${mod_id}']]
    modId = "fabric_api"
    mandatory = true
    versionRange = "[${forge_fabric_version},)"